name: Release  Upload

# 手动上传，防止大文件问题
# on:
#   release:
#     types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip the source directories
        run: |
          zip -r linux_py312_cu128_torch27.zip wheels/py312_cu128_torch2.7/linux
          zip -r win_py312_cu128_torch27.zip wheels/py312_cu128_torch2.7/win

      - name: Upload linux_py312_cu128_torch27.zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./linux_py312_cu128_torch27.zip
          asset_name: linux_py312_cu128_torch27.zip
          asset_content_type: application/zip

      - name: Upload win_py312_cu128_torch27.zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./win_py312_cu128_torch27.zip
          asset_name: win_py312_cu128_torch27.zip
          asset_content_type: application/zip
    